name: Prepare next release ğŸš€

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run release draft to extract labels â˜•ï¸
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Autodetect labels ğŸ”
        uses: ./shared-actions/steps/dx/prepare-draft-release
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}
