name: Pull request preparation ğŸ«¡

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      # If unlabeled is enabled, it will prevent from manually remove the label x)
      #- labeled
      #- unlabeled

jobs:
  autodetect-labels:
    name: Autodetect labels ğŸ” 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Run autodetection
        uses: ./shared-actions/steps/dx/automatically-apply-labels
        with:
          appId: ${{ secrets.DEPLOY_APP_ID }}
          privateKey: ${{ secrets.DEPLOY_APP_KEY }}
